import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  FiArrowRight, FiBarChart2, FiCheck, FiClipboard, FiDollarSign, FiFeather,
  FiMenu, FiPackage, FiPieChart, FiShoppingBag, FiTrendingUp, FiUsers, FiX,
} from 'react-icons/fi';
import { FaWhatsapp } from 'react-icons/fa';
import { FaXTwitter } from 'react-icons/fa6';
import cloudFarmLogo from '../assets/CloudFarm_logo.png';
import livestockImage from '../assets/livestock.png';
import poultryImage from '../assets/poultry.png';
import eggImage from '../assets/egg.png';
import { formatCurrency, getBillingPeriodLabel, getPlanPrice, subscriptionPlans } from '../data/subscriptionPlans';
import { getWhatsappUrl, siteConfig } from '../config/siteConfig';

const featureCards = [
  { icon: FiFeather, title: 'Poultry management', text: 'Keep batches, bird quantities, age, stages, health, and sale prices organized.' },
  { icon: FiUsers, title: 'Livestock records', text: 'Track animals, tags, age, health, feed, costs, and sales from one workspace.' },
  { icon: FiPackage, title: 'Feed management', text: 'Record feed, monitor usage, and connect consumption with farm records.' },
  { icon: FiDollarSign, title: 'Expense tracking', text: 'Organize farm expenses so costs are easier to review when decisions are due.' },
  { icon: FiShoppingBag, title: 'Sales management', text: 'Record animals, birds, and egg sales with quantities, dates, revenue, and profit.' },
  { icon: FiPieChart, title: 'Egg Inventory', text: 'Follow egg production and understand feed-driven cost per egg and crate.' },
];

const problems = [
  ['Paper records get scattered', 'Bring farm information into structured digital records.'],
  ['Feed costs are hard to follow', 'Record consumption and connect feed cost to animals and birds.'],
  ['Sales and expenses live in different places', 'Keep income, costs, quantities, and dates in one farm workspace.'],
  ['Egg production costs are unclear', 'Use Egg Inventory to connect laying-bird feed use with egg cost.'],
];

const workflow = [
  ['01', 'Create your farm workspace', 'Set up your account and begin organizing poultry, livestock, feed, expenses, sales, and inventory.'],
  ['02', 'Record what happens each day', 'Capture production, consumption, costs, sales, and farm activity while the details are fresh.'],
  ['03', 'Review the farm with clarity', 'Use dashboards, history, exports, and reports to understand what is happening over time.'],
];

const LandingPage = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  const plans = subscriptionPlans.filter((plan) => ['starter', 'basic', 'premium'].includes(plan.key));
  const whatsappUrl = getWhatsappUrl();

  return (
    <div className="min-h-screen bg-white text-slate-900">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-emerald-800/20 bg-emerald-700/95 shadow-lg shadow-emerald-950/10 backdrop-blur">
        <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8">
          <Link to="/" className="flex items-center gap-3" aria-label="CloudFarm home"><img src={cloudFarmLogo} alt="CloudFarm logo" className="h-10 w-10 rounded-xl object-contain" /><span className="text-xl font-black tracking-tight text-white">CloudFarm</span></Link>
          <nav className="hidden items-center gap-7 text-sm font-semibold text-emerald-50 md:flex"><a href="#problem" className="hover:text-white">Why CloudFarm</a><a href="#features" className="hover:text-white">Features</a><a href="#plans" className="hover:text-white">Plans</a><Link to="/support/contact" className="hover:text-white">Support</Link></nav>
          <div className="hidden items-center gap-3 md:flex"><Link to="/login" className="px-3 py-2 text-sm font-bold text-white hover:text-emerald-100">Sign in</Link><Link to="/register" className="rounded-lg bg-white px-5 py-2.5 text-sm font-bold text-emerald-800 hover:bg-emerald-50">Get started</Link></div>
          <button type="button" onClick={() => setMenuOpen((open) => !open)} className="text-white md:hidden" aria-label="Toggle navigation">{menuOpen ? <FiX size={24} /> : <FiMenu size={24} />}</button>
        </div>
        {menuOpen && <div className="border-t border-emerald-600 bg-emerald-700 px-5 py-5 md:hidden"><nav className="flex flex-col gap-4 text-sm font-semibold text-emerald-50"><a href="#problem" onClick={() => setMenuOpen(false)}>Why CloudFarm</a><a href="#features" onClick={() => setMenuOpen(false)}>Features</a><a href="#plans" onClick={() => setMenuOpen(false)}>Plans</a><Link to="/support/contact">Support</Link><div className="flex gap-4 border-t border-emerald-600 pt-4"><Link to="/login">Sign in</Link><Link to="/register" className="text-white">Get started</Link></div></nav></div>}
      </header>

      <main className="pt-[76px]">
        <section className="relative overflow-hidden bg-emerald-50"><div className="absolute -right-24 -top-24 h-96 w-96 rounded-full border-[26px] border-white/70" /><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 lg:grid-cols-[.95fr_1.05fr] lg:px-8 lg:py-24"><div className="relative z-10 cloudfarm-fade-up"><p className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-emerald-700"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Farm management for real work</p><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.02] tracking-tight text-emerald-950 sm:text-6xl lg:text-7xl">Know your farm. Run it with confidence.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">CloudFarm helps poultry and livestock farmers keep records, follow feed and costs, manage sales and expenses, and understand farm activity from one clear workspace.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/register" className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-6 py-3.5 font-bold text-white shadow-lg shadow-emerald-200 hover:bg-emerald-700">Start managing your farm <FiArrowRight /></Link><a href="#features" className="inline-flex items-center justify-center gap-2 rounded-lg border border-emerald-200 bg-white px-6 py-3.5 font-bold text-emerald-800 hover:border-emerald-500">Explore features</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-sm font-semibold text-emerald-800"><span><FiCheck className="mr-1 inline" /> Digital farm records</span><span><FiCheck className="mr-1 inline" /> Cost visibility</span><span><FiCheck className="mr-1 inline" /> Daily activity tracking</span></div></div><div className="relative grid grid-cols-2 gap-4 sm:gap-6 cloudfarm-fade-up" style={{ animationDelay: '120ms' }}><div className="col-span-2 overflow-hidden rounded-3xl border-8 border-white bg-white shadow-2xl shadow-emerald-900/15"><img src={poultryImage} alt="Poultry management in CloudFarm" className="h-56 w-full object-cover sm:h-72" /></div><div className="overflow-hidden rounded-3xl border-8 border-white bg-white shadow-xl"><img src={livestockImage} alt="Livestock management in CloudFarm" className="h-40 w-full object-cover sm:h-52" /></div><div className="overflow-hidden rounded-3xl border-8 border-white bg-white shadow-xl"><img src={eggImage} alt="Egg inventory management in CloudFarm" className="h-40 w-full object-cover sm:h-52" /></div></div></div></section>

        <section id="problem" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">The daily challenge</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">When farm information is scattered, decisions get harder.</h2><p className="mt-5 leading-8 text-slate-600">Paper notes, memory, separate notebooks, and delayed calculations make it difficult to see the full picture of your operation. CloudFarm gives those details a place to live.</p></div><div className="grid gap-4 sm:grid-cols-2">{problems.map(([title, solution], index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm cloudfarm-fade-up" style={{ animationDelay: `${index * 80}ms` }}><span className="text-sm font-black text-emerald-600">0{index + 1}</span><h3 className="mt-5 text-lg font-black text-emerald-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{solution}</p></article>)}</div></div></section>

        <section className="border-y border-emerald-100 bg-emerald-950 text-white"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-300">From problem to practice</p><h2 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">A clearer operating rhythm for the farm.</h2></div><div className="grid gap-8 sm:grid-cols-3">{workflow.map(([number, title, text]) => <div key={number} className="border-t border-emerald-700 pt-5"><span className="text-sm font-black text-emerald-300">{number}</span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 leading-7 text-emerald-100/75">{text}</p></div>)}</div></div></div></section>

        <section id="features" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="max-w-2xl"><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Built around the work</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">The farm tools you use, connected.</h2><p className="mt-5 text-lg leading-8 text-slate-600">CloudFarm keeps the main parts of your poultry and livestock operation together so the records are easier to follow.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featureCards.map(({ icon: Icon, title, text }, index) => <article key={title} className="border border-emerald-100 border-t-2 border-t-emerald-600 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl cloudfarm-fade-up" style={{ animationDelay: `${index * 70}ms` }}><span className="inline-flex rounded-xl bg-emerald-100 p-3 text-emerald-700"><Icon size={24} /></span><h3 className="mt-5 text-xl font-black text-emerald-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></article>)}</div></section>

        <section className="bg-slate-50"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid items-center gap-10 lg:grid-cols-2"><div className="overflow-hidden rounded-3xl bg-white shadow-xl"><img src={livestockImage} alt="Livestock records and monitoring" className="h-80 w-full object-cover sm:h-[420px]" /></div><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Poultry and livestock</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">Understand what each animal and batch needs.</h2><p className="mt-5 leading-8 text-slate-600">Store poultry and livestock records, follow quantities and age in days or weeks, review feed consumption, and keep health and cost information close to the record it belongs to.</p><ul className="mt-7 grid gap-3 text-sm font-semibold text-slate-700 sm:grid-cols-2"><li><FiCheck className="mr-2 inline text-emerald-600" /> Batch and tag records</li><li><FiCheck className="mr-2 inline text-emerald-600" /> Age and stage tracking</li><li><FiCheck className="mr-2 inline text-emerald-600" /> Feed cost visibility</li><li><FiCheck className="mr-2 inline text-emerald-600" /> Sales-ready inventory</li></ul></div></div></div></section>

        <section className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Feed, expenses, and sales</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">See the costs and activity behind the operation.</h2><p className="mt-5 max-w-2xl leading-8 text-slate-600">Record feed and monitor consumption, organize farm expenses, and capture sales for poultry, livestock, and eggs. Where the application calculates costs and profit, those values stay connected to the underlying records.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><FiPackage className="text-emerald-700" size={23} /><h3 className="mt-4 font-black text-emerald-950">Feed</h3><p className="mt-2 text-sm leading-6 text-slate-600">Record usage and follow consumption.</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><FiDollarSign className="text-emerald-700" size={23} /><h3 className="mt-4 font-black text-emerald-950">Expenses</h3><p className="mt-2 text-sm leading-6 text-slate-600">Keep operating costs organized.</p></div><div className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><FiTrendingUp className="text-emerald-700" size={23} /><h3 className="mt-4 font-black text-emerald-950">Sales</h3><p className="mt-2 text-sm leading-6 text-slate-600">Review quantity, revenue, and profit.</p></div></div></div><div className="overflow-hidden rounded-3xl bg-white shadow-xl"><img src={poultryImage} alt="Poultry feed and sales records" className="h-80 w-full object-cover" /></div></div></section>

        <section className="border-y border-emerald-100 bg-emerald-50"><div className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-24"><div className="grid items-center gap-10 lg:grid-cols-[.9fr_1.1fr]"><div className="overflow-hidden rounded-3xl bg-white shadow-xl"><img src={eggImage} alt="CloudFarm Egg Inventory" className="h-80 w-full object-cover sm:h-96" /></div><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">A closer look at Egg Inventory</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">Connect laying-bird feed to the cost of an egg.</h2><p className="mt-5 leading-8 text-slate-600">Egg Inventory helps organize production and cost records. The idea is simple: feed consumed by laying birds becomes a feed cost, that cost is connected to egg production, and the application calculates cost values such as cost per egg and crate where the available records support it.</p><div className="mt-7 grid items-center gap-3 text-center text-sm font-black text-emerald-800 sm:grid-cols-3"><div className="rounded-xl bg-white p-4 shadow-sm">Feed consumed</div><FiArrowRight className="mx-auto hidden sm:block" /><div className="rounded-xl bg-white p-4 shadow-sm">Feed cost</div><FiArrowRight className="mx-auto hidden sm:block" /><div className="rounded-xl bg-white p-4 shadow-sm">Egg cost</div></div></div></div></div></section>

        <section id="plans" className="mx-auto max-w-7xl px-5 py-20 lg:px-8 lg:py-28"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Start at your pace</p><h2 className="mt-3 text-4xl font-black tracking-tight text-emerald-950 sm:text-5xl">A plan for the next stage of your farm.</h2></div><Link to="/subscription" className="font-bold text-emerald-700 hover:text-emerald-900">Compare plans <FiArrowRight className="inline" /></Link></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map((plan) => <article key={plan.key} className={`relative flex flex-col border p-7 transition duration-300 hover:-translate-y-1 ${plan.recommended ? 'border-emerald-600 bg-emerald-600 text-white shadow-xl shadow-emerald-200' : 'border-emerald-100 bg-white shadow-sm hover:border-emerald-300 hover:shadow-xl'}`}>{plan.recommended && <span className="absolute right-5 top-5 rounded-full bg-white px-3 py-1 text-xs font-black uppercase tracking-widest text-emerald-700">Recommended</span>}<h3 className="text-2xl font-black">{plan.name}</h3><p className={`mt-3 min-h-14 leading-6 ${plan.recommended ? 'text-emerald-50' : 'text-slate-600'}`}>{plan.description}</p><p className="mt-7 text-3xl font-black">{formatCurrency(getPlanPrice(plan))}<span className={`text-sm font-semibold ${plan.recommended ? 'text-emerald-100' : 'text-slate-500'}`}>{getBillingPeriodLabel()}</span></p><ul className={`mt-7 space-y-3 text-sm ${plan.recommended ? 'text-white' : 'text-slate-600'}`}>{plan.features.slice(0, 5).map((feature) => <li key={feature}><FiCheck className="mr-2 inline text-emerald-500" />{feature}</li>)}</ul><Link to="/register" className={`mt-8 inline-flex items-center justify-center rounded-lg px-5 py-3 font-bold ${plan.recommended ? 'bg-white text-emerald-700 hover:bg-emerald-50' : 'bg-emerald-600 text-white hover:bg-emerald-700'}`}>Get started</Link></article>)}</div></section>

        <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8 lg:pb-28"><div className="rounded-3xl bg-emerald-100 px-7 py-12 sm:px-12"><div className="flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><div><p className="text-sm font-black uppercase tracking-[.18em] text-emerald-700">Ready for a clearer farm record?</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-tight text-emerald-950">Take control of the information behind every farm decision.</h2></div><Link to="/register" className="inline-flex shrink-0 items-center gap-2 rounded-lg bg-emerald-600 px-6 py-3.5 font-bold text-white hover:bg-emerald-700">Start with CloudFarm <FiArrowRight /></Link></div></div></section>
      </main>

      <footer className="bg-emerald-950 text-emerald-50"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-12 lg:grid-cols-[1.4fr_1fr_1fr] lg:px-8"><div><div className="flex items-center gap-3"><img src={cloudFarmLogo} alt="CloudFarm logo" className="h-10 w-10 rounded-xl object-contain" /><span className="text-xl font-black">CloudFarm</span></div><p className="mt-4 max-w-sm leading-7 text-emerald-100/70">Organized farm records for poultry and livestock operations.</p></div><div><p className="font-black">Explore</p><div className="mt-4 flex flex-col gap-3 text-sm text-emerald-100/70"><a href="#problem" className="hover:text-white">Why CloudFarm</a><a href="#features" className="hover:text-white">Features</a><a href="#plans" className="hover:text-white">Plans</a></div></div><div><p className="font-black">Account</p><div className="mt-4 flex flex-col gap-3 text-sm text-emerald-100/70"><Link to="/login" className="hover:text-white">Login</Link><Link to="/register" className="hover:text-white">Get started</Link><Link to="/support/contact" className="hover:text-white">Contact support</Link>{siteConfig.support.xUrl && <a href={siteConfig.support.xUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 hover:text-white"><FaXTwitter /> Follow on X</a>}</div></div></div><div className="border-t border-emerald-800"><div className="mx-auto max-w-7xl px-5 py-5 text-xs text-emerald-100/50 lg:px-8">© {new Date().getFullYear()} CloudFarm. All rights reserved.</div></div></footer>

      {whatsappUrl && <a href={whatsappUrl} target="_blank" rel="noreferrer" aria-label="Chat with CloudFarm support on WhatsApp" className="fixed bottom-5 right-5 z-50 inline-flex h-14 w-14 items-center justify-center rounded-full bg-[#25D366] text-white shadow-xl shadow-emerald-950/20 transition hover:-translate-y-1 hover:bg-[#1ebe5d] sm:bottom-7 sm:right-7"><FaWhatsapp size={28} /></a>}
    </div>
  );
};

export default LandingPage;
