const express = require('express')
const { authMiddleware, checkPermission, isManager } = require('../middleweres/authMiddlewere')
const { attachFarmDB } = require('../middleware/dbMiddleware')
const { checkSubscription } = require('../middleware/subscriptionMiddleware')
const { createPoultry, getPoultry, getAvailablePoultry, getSoldPoultry, getPoultryById, editPoultry, removePoultry, poultryCount } = require('../controllers/poultryController')
const { validate } = require('../middleweres/validation')
const { poultryValidation } = require('../middleweres/controllerValidation')
const { asyncHandler } = require('../middleware/errorHandler')
const { auditMiddleware } = require('../middleware/auditLogger')
const router = express.Router()

router.post('/add-poultry', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), validate(poultryValidation), auditMiddleware('CREATE_POULTRY', 'poultry'), asyncHandler(createPoultry))
router.get('/list', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), asyncHandler(getPoultry))
router.get('/available', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), asyncHandler(getAvailablePoultry))
router.get('/sold', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), asyncHandler(getSoldPoultry))
router.get('/count', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), asyncHandler(poultryCount))
router.get('/:id', authMiddleware, checkSubscription, attachFarmDB, checkPermission('poultry'), asyncHandler(getPoultryById))
router.put('/edit/:id', authMiddleware, isManager, checkSubscription, attachFarmDB, checkPermission('poultry'), validate(poultryValidation), auditMiddleware('UPDATE_POULTRY', 'poultry'), asyncHandler(editPoultry))
router.delete('/:id', authMiddleware, isManager, checkSubscription, attachFarmDB, checkPermission('poultry'), auditMiddleware('DELETE_POULTRY', 'poultry'), asyncHandler(removePoultry))

module.exports = router